import { z } from "zod"

const optionalNonEmptyString = z.preprocess((value) => {
  if (typeof value !== "string") return value
  const trimmed = value.trim()
  return trimmed.length === 0 ? undefined : trimmed
}, z.string().min(1).optional())

const serverEnvSchema = z.object({
  NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1),
  SUPABASE_SERVICE_ROLE_KEY: optionalNonEmptyString,
  SUPABASE_JWT_SECRET: optionalNonEmptyString,
  STRIPE_SECRET_KEY: optionalNonEmptyString,
  STRIPE_TEST_SECRET_KEY: optionalNonEmptyString,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: optionalNonEmptyString,
  NEXT_PUBLIC_STRIPE_TEST_PUBLISHABLE_KEY: optionalNonEmptyString,
  STRIPE_WEBHOOK_SECRET: optionalNonEmptyString,
  STRIPE_TEST_WEBHOOK_SECRET: optionalNonEmptyString,
  STRIPE_ORGANIZATION_PRICE_ID: optionalNonEmptyString,
  STRIPE_OPERATIONS_SUPPORT_PRICE_ID: optionalNonEmptyString,
  STRIPE_TEST_ORGANIZATION_PRICE_ID: optionalNonEmptyString,
  STRIPE_TEST_OPERATIONS_SUPPORT_PRICE_ID: optionalNonEmptyString,
  STRIPE_ACCELERATOR_WITH_COACHING_PRICE_ID: optionalNonEmptyString,
  STRIPE_ACCELERATOR_WITHOUT_COACHING_PRICE_ID: optionalNonEmptyString,
  STRIPE_ACCELERATOR_WITH_COACHING_MONTHLY_PRICE_ID: optionalNonEmptyString,
  STRIPE_ACCELERATOR_WITHOUT_COACHING_MONTHLY_PRICE_ID: optionalNonEmptyString,
  STRIPE_ACCELERATOR_PRICE_ID: optionalNonEmptyString,
  STRIPE_ELECTIVE_RETENTION_AND_SECURITY_PRICE_ID: optionalNonEmptyString,
  STRIPE_ELECTIVE_DUE_DILIGENCE_PRICE_ID: optionalNonEmptyString,
  STRIPE_ELECTIVE_FINANCIAL_HANDBOOK_PRICE_ID: optionalNonEmptyString,
  NEXT_PUBLIC_MEETING_FREE_URL: optionalNonEmptyString,
  NEXT_PUBLIC_MEETING_DISCOUNTED_URL: optionalNonEmptyString,
  NEXT_PUBLIC_MEETING_FULL_URL: optionalNonEmptyString,
  NEXT_PUBLIC_MAPBOX_TOKEN: optionalNonEmptyString,
})

const clientEnvSchema = serverEnvSchema.pick({
  NEXT_PUBLIC_SUPABASE_URL: true,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: true,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: true,
  NEXT_PUBLIC_STRIPE_TEST_PUBLISHABLE_KEY: true,
  NEXT_PUBLIC_MAPBOX_TOKEN: true,
})

type ServerEnv = z.infer<typeof serverEnvSchema>
type ClientEnv = z.infer<typeof clientEnvSchema>

function assertEnv<TSchema extends z.ZodTypeAny>(schema: TSchema, input: unknown) {
  const parsed = schema.safeParse(input)

  if (!parsed.success) {
    const formatted = parsed.error.issues
      .map((issue) => `${issue.path.join(".") || "unknown"}: ${issue.message}`)
      .join("; ")

    throw new Error(`Invalid environment variables: ${formatted}`)
  }

  return parsed.data
}

const PLACEHOLDER_SUPABASE_URL = "https://placeholder.supabase.co"
const PLACEHOLDER_SUPABASE_ANON_KEY = "public-anon-placeholder"

export const env: ServerEnv = assertEnv(serverEnvSchema, {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? PLACEHOLDER_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY:
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? PLACEHOLDER_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  SUPABASE_JWT_SECRET: process.env.SUPABASE_JWT_SECRET,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_TEST_SECRET_KEY: process.env.STRIPE_TEST_SECRET_KEY,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  NEXT_PUBLIC_STRIPE_TEST_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_TEST_PUBLISHABLE_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  STRIPE_TEST_WEBHOOK_SECRET: process.env.STRIPE_TEST_WEBHOOK_SECRET,
  STRIPE_ORGANIZATION_PRICE_ID: process.env.STRIPE_ORGANIZATION_PRICE_ID,
  STRIPE_OPERATIONS_SUPPORT_PRICE_ID: process.env.STRIPE_OPERATIONS_SUPPORT_PRICE_ID,
  STRIPE_TEST_ORGANIZATION_PRICE_ID: process.env.STRIPE_TEST_ORGANIZATION_PRICE_ID,
  STRIPE_TEST_OPERATIONS_SUPPORT_PRICE_ID: process.env.STRIPE_TEST_OPERATIONS_SUPPORT_PRICE_ID,
  STRIPE_ACCELERATOR_WITH_COACHING_PRICE_ID: process.env.STRIPE_ACCELERATOR_WITH_COACHING_PRICE_ID,
  STRIPE_ACCELERATOR_WITHOUT_COACHING_PRICE_ID: process.env.STRIPE_ACCELERATOR_WITHOUT_COACHING_PRICE_ID,
  STRIPE_ACCELERATOR_WITH_COACHING_MONTHLY_PRICE_ID:
    process.env.STRIPE_ACCELERATOR_WITH_COACHING_MONTHLY_PRICE_ID,
  STRIPE_ACCELERATOR_WITHOUT_COACHING_MONTHLY_PRICE_ID:
    process.env.STRIPE_ACCELERATOR_WITHOUT_COACHING_MONTHLY_PRICE_ID,
  STRIPE_ACCELERATOR_PRICE_ID: process.env.STRIPE_ACCELERATOR_PRICE_ID,
  STRIPE_ELECTIVE_RETENTION_AND_SECURITY_PRICE_ID:
    process.env.STRIPE_ELECTIVE_RETENTION_AND_SECURITY_PRICE_ID,
  STRIPE_ELECTIVE_DUE_DILIGENCE_PRICE_ID: process.env.STRIPE_ELECTIVE_DUE_DILIGENCE_PRICE_ID,
  STRIPE_ELECTIVE_FINANCIAL_HANDBOOK_PRICE_ID:
    process.env.STRIPE_ELECTIVE_FINANCIAL_HANDBOOK_PRICE_ID,
  NEXT_PUBLIC_MEETING_FREE_URL: process.env.NEXT_PUBLIC_MEETING_FREE_URL,
  NEXT_PUBLIC_MEETING_DISCOUNTED_URL: process.env.NEXT_PUBLIC_MEETING_DISCOUNTED_URL,
  NEXT_PUBLIC_MEETING_FULL_URL: process.env.NEXT_PUBLIC_MEETING_FULL_URL,
  NEXT_PUBLIC_MAPBOX_TOKEN: process.env.NEXT_PUBLIC_MAPBOX_TOKEN,
})

export const clientEnv: ClientEnv = assertEnv(clientEnvSchema, {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? PLACEHOLDER_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY:
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? PLACEHOLDER_SUPABASE_ANON_KEY,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  NEXT_PUBLIC_STRIPE_TEST_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_TEST_PUBLISHABLE_KEY,
  NEXT_PUBLIC_MAPBOX_TOKEN: process.env.NEXT_PUBLIC_MAPBOX_TOKEN,
})
