import type { DocumentDefinition } from "./types"

export const MAX_UPLOAD_MB = 50
export const MAX_BYTES = MAX_UPLOAD_MB * 1024 * 1024

export const DOCUMENTS: DocumentDefinition[] = [
  {
    kind: "verification-letter",
    key: "verificationLetter",
    title: "501(c)(3) determination letter",
    description: "IRS determination letter confirming nonprofit status.",
    defaultName: "Verification letter",
    category: "Compliance",
  },
  {
    kind: "articles-of-incorporation",
    key: "articlesOfIncorporation",
    title: "Articles of incorporation",
    description: "Stamped incorporation filing from your state.",
    defaultName: "Articles of incorporation",
    category: "Governance",
  },
  {
    kind: "bylaws",
    key: "bylaws",
    title: "Bylaws",
    description: "Current governing bylaws or constitution.",
    defaultName: "Bylaws",
    category: "Governance",
  },
  {
    kind: "state-registration",
    key: "stateRegistration",
    title: "State registration",
    description: "State-level charity or nonprofit registration proof.",
    defaultName: "State registration",
    category: "Compliance",
  },
  {
    kind: "good-standing-certificate",
    key: "goodStandingCertificate",
    title: "Certificate of good standing",
    description: "Certificate showing active standing with your state.",
    defaultName: "Good standing certificate",
    category: "Compliance",
  },
  {
    kind: "w9",
    key: "w9",
    title: "W-9 form",
    description: "Current IRS W-9 for payment and grant workflows.",
    defaultName: "W-9",
    category: "Finance",
  },
  {
    kind: "tax-exempt-certificate",
    key: "taxExemptCertificate",
    title: "Tax exempt certificate",
    description: "State tax-exempt certificate where applicable.",
    defaultName: "Tax exempt certificate",
    category: "Compliance",
  },
  {
    kind: "uei-confirmation",
    key: "ueiConfirmation",
    title: "UEI confirmation",
    description: "SAM registration screenshot or confirmation for your UEI.",
    defaultName: "UEI confirmation (SAM screenshot)",
    category: "Compliance",
  },
  {
    kind: "sam-active-status",
    key: "samActiveStatus",
    title: "SAM.gov active status",
    description: "Current SAM active status record with expiration date.",
    defaultName: "SAM.gov active status",
    category: "Compliance",
  },
  {
    kind: "grants-gov-registration",
    key: "grantsGovRegistration",
    title: "Grants.gov registration confirmation",
    description: "Proof of active Grants.gov registration.",
    defaultName: "Grants.gov registration confirmation",
    category: "Fundraising",
  },
  {
    kind: "gata-pre-qualification",
    key: "gataPreQualification",
    title: "GATA pre-qualification",
    description: "Illinois GATA pre-qualification documentation (if applicable).",
    defaultName: "GATA pre-qualification (Illinois only)",
    category: "Compliance",
  },
  {
    kind: "ein-confirmation-letter",
    key: "einConfirmationLetter",
    title: "EIN confirmation letter (CP 575)",
    description: "IRS CP 575 EIN confirmation letter.",
    defaultName: "EIN confirmation letter (CP 575)",
    category: "Finance",
  },
  {
    kind: "irs-990s",
    key: "irs990s",
    title: "IRS Form 990s",
    description: "Most recent three years of IRS Form 990 filings.",
    defaultName: "990s (last 3 years)",
    category: "Finance",
  },
  {
    kind: "audited-financials",
    key: "auditedFinancials",
    title: "Audited financials",
    description: "Audited financial statements (if applicable).",
    defaultName: "Audited financials",
    category: "Finance",
  },
]

export const ROADMAP_CATEGORY_BY_ID: Record<string, string> = {
  origin_story: "Roadmap",
  need: "Roadmap",
  mission_vision_values: "Roadmap",
  theory_of_change: "Roadmap",
  program: "Programs",
  evaluation: "Programs",
  people: "Operations",
  budget: "Finance",
  fundraising: "Fundraising",
  fundraising_strategy: "Fundraising",
  fundraising_presentation: "Fundraising",
  fundraising_crm_plan: "Fundraising",
  communications: "Communications",
  board_strategy: "Board",
  board_calendar: "Board",
  board_handbook: "Board",
  next_actions: "Operations",
}

export const POLICY_CATEGORY_PRESETS = [
  "Board",
  "Fundraising",
  "Finance",
  "Governance",
  "Operations",
  "Compliance",
  "HR",
] as const
