export const ORG_BANNER_ASPECT_RATIO = 4 / 1
export const ORG_BANNER_TARGET_WIDTH = 2400
export const ORG_BANNER_TARGET_HEIGHT = 600
export const ORG_BANNER_MIN_WIDTH = 1600
export const ORG_BANNER_MIN_HEIGHT = 400

export const ORG_BANNER_RECOMMENDED_DIMENSIONS_LABEL = `${ORG_BANNER_TARGET_WIDTH}×${ORG_BANNER_TARGET_HEIGHT}`
export const ORG_BANNER_MIN_DIMENSIONS_LABEL = `${ORG_BANNER_MIN_WIDTH}×${ORG_BANNER_MIN_HEIGHT}`
export const ORG_BANNER_ASPECT_LABEL = "4:1"
