export type WorkspaceCanvasPoint = {
  x: number
  y: number
}

export const WORKSPACE_PERSON_RELATIONSHIP_RING_GAP = 54
export const WORKSPACE_PERSON_RELATIONSHIP_MIN_RADIUS = 340
export const WORKSPACE_PERSON_RELATIONSHIP_MAX_RADIUS = 680
export const WORKSPACE_PERSON_RELATIONSHIP_CARD_GAP = 180
export const WORKSPACE_PERSON_RELATIONSHIP_LEVEL_GAP = 118
export const WORKSPACE_PERSON_RELATIONSHIP_ROOT_GAP = 72
export const WORKSPACE_PERSON_RELATIONSHIP_SIBLING_GAP = 44
export const WORKSPACE_PERSON_RELATIONSHIP_MAX_ROOT_COLUMNS = 4
export const WORKSPACE_PERSON_RELATIONSHIP_MAX_LEVEL_COLUMNS = 4
export const WORKSPACE_PERSON_RELATIONSHIP_GRID_THRESHOLD = 5
