"use client"

import { z } from "zod"
import { publicSharingEnabled } from "@/lib/feature-flags"

export const PROGRAM_TYPES = [
  "Direct Services",
  "Community Support",
  "Resource Distribution",
  "Training & Capacity Building",
  "Advocacy & Organizing",
  "Research & Information",
  "Culture & Public Benefit",
] as const

export const DELIVERY_FORMATS = [
  "Cohort",
  "Drop-in Hours",
  "1:1 Support",
  "One-time Event",
  "Outreach Campaign",
  "Distribution",
  "Workforce Pathway",
  "Peer Group",
  "Digital",
  "Referral",
] as const

export const LOCATION_MODES = ["in_person", "online", "hybrid"] as const

const monthRegex = /^\d{4}-(0[1-9]|1[0-2])$/

export const ProgramWizardSchema = z.object({
  title: z.string().trim().min(1).max(160),
  oneSentence: z.string().trim().min(1).max(240),
  subtitle: z.string().max(200).or(z.literal("")).default(""),
  imageUrl: z.string().url().or(z.literal("")).default(""),
  programType: z.enum(PROGRAM_TYPES),
  coreFormat: z.enum(DELIVERY_FORMATS),
  formatAddons: z.array(z.string().min(1)).default([]),
  servesWho: z.string().trim().min(1).max(400),
  eligibilityRules: z.string().max(400).or(z.literal("")).default(""),
  participantReceive1: z.string().trim().min(1).max(200),
  participantReceive2: z.string().trim().min(1).max(200),
  participantReceive3: z.string().trim().min(1).max(200),
  successOutcome1: z.string().trim().min(1).max(220),
  successOutcome2: z.string().max(220).or(z.literal("")).default(""),
  successOutcome3: z.string().max(220).or(z.literal("")).default(""),
  pilotPeopleServed: z.coerce.number().int().min(1),
  staffCount: z.coerce.number().int().min(1),
  volunteerCount: z.coerce.number().int().min(0).default(0),
  staffRoles: z
    .array(
      z.object({
        role: z.string().trim().min(1).max(120),
        hoursPerWeek: z.coerce.number().min(0).max(168),
      }),
    )
    .default([]),
  startMonth: z.string().regex(monthRegex),
  durationLabel: z.string().trim().min(1).max(120),
  frequency: z.string().trim().min(1).max(120),
  locationMode: z.enum(LOCATION_MODES),
  locationDetails: z.string().max(200).or(z.literal("")).default(""),
  budgetUsd: z.coerce.number().min(1),
  costStaffUsd: z.coerce.number().nonnegative().default(0),
  costSpaceUsd: z.coerce.number().nonnegative().default(0),
  costMaterialsUsd: z.coerce.number().nonnegative().default(0),
  costOtherUsd: z.coerce.number().nonnegative().default(0),
  fundingSource: z.string().max(220).or(z.literal("")).default(""),
  statusLabel: z.string().max(60).or(z.literal("Draft")).default("Draft"),
  ctaLabel: z.string().max(40).or(z.literal("Learn more")).default("Learn more"),
  ctaUrl: z.string().url().or(z.literal("")).default(""),
  goalUsd: z.coerce.number().nonnegative().default(0),
  raisedUsd: z.coerce.number().nonnegative().default(0),
  features: z.array(z.string().min(1)).default([]),
  isPublic: z.boolean().default(publicSharingEnabled),
  // Legacy fields kept for backwards compatibility with existing wizard step modules.
  description: z.string().max(2000).or(z.literal("")).default(""),
  location: z.string().max(160).or(z.literal("")).default(""),
  locationType: z.enum(["in_person", "online"]).default("in_person"),
  locationUrl: z.string().url().or(z.literal("")).default(""),
  teamIds: z.array(z.string().min(1)).default([]),
  startDate: z.string().or(z.literal("")).default(""),
  endDate: z.string().or(z.literal("")).default(""),
  addressStreet: z.string().max(200).or(z.literal("")).default(""),
  addressCity: z.string().max(120).or(z.literal("")).default(""),
  addressState: z.string().max(120).or(z.literal("")).default(""),
  addressPostal: z.string().max(40).or(z.literal("")).default(""),
  addressCountry: z.string().max(120).or(z.literal("")).default(""),
})

export type ProgramWizardFormState = z.infer<typeof ProgramWizardSchema>

export const defaultProgramWizardForm: ProgramWizardFormState = {
  title: "",
  oneSentence: "",
  subtitle: "",
  imageUrl: "",
  description: "",
  location: "",
  locationType: "in_person",
  locationUrl: "",
  teamIds: [],
  startDate: "",
  endDate: "",
  addressStreet: "",
  addressCity: "",
  addressState: "",
  addressPostal: "",
  addressCountry: "",
  programType: "Direct Services",
  coreFormat: "Cohort",
  formatAddons: [],
  servesWho: "",
  eligibilityRules: "",
  participantReceive1: "",
  participantReceive2: "",
  participantReceive3: "",
  successOutcome1: "",
  successOutcome2: "",
  successOutcome3: "",
  pilotPeopleServed: 25,
  staffCount: 2,
  volunteerCount: 0,
  staffRoles: [],
  startMonth: "",
  durationLabel: "",
  frequency: "Weekly",
  locationMode: "in_person",
  locationDetails: "",
  budgetUsd: 25000,
  costStaffUsd: 15000,
  costSpaceUsd: 5000,
  costMaterialsUsd: 3000,
  costOtherUsd: 2000,
  fundingSource: "",
  statusLabel: "Draft",
  ctaLabel: "Learn more",
  ctaUrl: "",
  goalUsd: 0,
  raisedUsd: 0,
  features: [],
  isPublic: publicSharingEnabled,
}
