import { expect, test } from "@playwright/test"

// These interaction assertions also run against the existing dev server on macOS;
// screenshot comparisons still use the guarded repository visual config in CI.
const fixture = `${process.env.PLAYWRIGHT_BASE_URL ?? ""}/visual-regression/project-feedback?scenario=editors`
test.use({ extraHTTPHeaders: { "x-coach-house-visual-regression": "1" } })

for (const width of [1440, 390]) {
  test(`task opens above a scrolled transformed list and restores focus (${width})`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    await page.goto(fixture)
    const list = page.getByTestId("task-list-scroll")
    await list.evaluate((element) => { element.scrollTop = 500 })
    const opener = page.getByRole("button", { name: "Open task", exact: true })
    await opener.click()
    const dialog = page.getByRole("dialog", { name: "Edit task" })
    await expect(dialog.locator("#task-create-title")).toHaveValue("Review staff meeting structure")
    const bounds = await dialog.boundingBox()
    expect(bounds!.y).toBeGreaterThanOrEqual(15)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(829)
    expect(bounds!.x).toBeGreaterThanOrEqual(15)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width - 15)
    await dialog.getByRole("button", { name: "To do", exact: true }).click()
    await page.getByRole("option", { name: "In progress", exact: true }).click()
    await dialog.getByRole("button", { name: "Assignee" }).click()
    await page.getByRole("option", { name: "Sample reviewer" }).click()
    await expect(dialog.getByRole("button", { name: "Sample reviewer" })).toBeVisible()
    await dialog.getByRole("button", { name: "Start date", exact: true }).click()
    await expect(page.locator('[data-slot="calendar"]')).toBeVisible()
    await page.keyboard.press("Escape")
    await expect(dialog).toBeVisible()
    await dialog.locator("#task-create-title").fill("Reviewed sample task")
    await dialog.getByRole("button", { name: "Save changes", exact: true }).click()
    await expect(dialog).toBeHidden()
    await expect(page.getByRole("status").filter({ hasText: "Task saved" })).toBeVisible()
    await expect(opener).toBeFocused()
    await expect.poll(() => list.evaluate((element) => element.scrollTop)).toBe(500)
    await opener.click()
    await expect(dialog.locator("#task-create-title")).toHaveValue("Reviewed sample task")
    await expect(dialog.getByRole("button", { name: "In progress", exact: true })).toBeVisible()
    await page.keyboard.press("Escape")
    await expect(dialog).toBeHidden()
    await expect(opener).toBeFocused()
    await expect.poll(() => page.locator("body").evaluate((element) => getComputedStyle(element).pointerEvents)).not.toBe("none")
  })

  for (const title of ["Mission", "Vision"]) {
    test(`${title} supports wheel and keyboard scrolling without losing controls (${width})`, async ({ page }) => {
      await page.setViewportSize({ width, height: 844 })
      await page.goto(fixture)
      await page.getByRole("button", { name: `Open ${title}`, exact: true }).click()
      const dialog = page.getByRole("dialog", { name: title, exact: true })
      const editor = dialog.locator(".ProseMirror")
      await expect(editor).toContainText(`${title} paragraph 70`)
      const original = await editor.innerHTML()
      const scroller = dialog.locator(".overflow-y-auto").first()
      const bounds = await scroller.boundingBox()
      await page.mouse.move(bounds!.x + bounds!.width / 2, bounds!.y + bounds!.height / 2)
      await page.mouse.wheel(0, 650)
      await expect.poll(() => scroller.evaluate((element) => element.scrollTop)).toBeGreaterThan(100)
      const before = await scroller.evaluate((element) => element.scrollTop)
      await page.mouse.wheel(0, -300)
      await expect.poll(() => scroller.evaluate((element) => element.scrollTop)).toBeLessThan(before)
      const save = dialog.getByRole("button", { name: "Save document", exact: true })
      await expect(save).toBeInViewport()
      await expect(save).toBeDisabled()
      await editor.focus()
      await page.keyboard.press(process.platform === "darwin" ? "Meta+ArrowDown" : "Control+End")
      await expect(editor.locator("p").last()).toBeInViewport()
      await page.keyboard.insertText(" Temporary review edit.")
      await expect(save).toBeEnabled()
      await save.focus()
      await expect(save).toBeFocused()
      await expect(save).toBeInViewport()
      page.once("dialog", (confirmation) => confirmation.accept())
      await dialog.getByRole("button", { name: "Cancel", exact: true }).click()
      await expect(dialog).toBeHidden()
      await page.getByRole("button", { name: `Open ${title}`, exact: true }).click()
      await expect(editor).toContainText(`${title} paragraph 70`)
      expect(await editor.innerHTML()).toBe(original)
      await dialog.getByRole("button", { name: "Cancel", exact: true }).click()
    })
  }
}

test("shared note and file dialogs keep their primary actions and nested upload usable", async ({ page }) => {
  await page.goto(fixture)
  await page.getByRole("button", { name: "Add note", exact: true }).click()
  const note = page.getByRole("dialog", { name: "Create note", exact: true })
  await expect(note).toBeVisible()
  await note.getByPlaceholder("Note title").fill("Sample note")
  await note.getByRole("button", { name: "Create Note", exact: true }).click()
  await expect(note).toBeHidden()
  await expect(page.getByRole("status").filter({ hasText: "Note saved" })).toBeVisible()
  await page.getByRole("button", { name: "Add File", exact: true }).click()
  const file = page.getByRole("dialog", { name: "Add file", exact: true })
  await expect(file).toBeVisible()
  await file.getByRole("button", { name: "Upload files", exact: true }).click()
  const upload = page.getByRole("dialog", { name: "Upload Files", exact: true })
  await expect(upload).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(upload).toBeHidden()
  await expect(file).toBeVisible()
  await file.locator("#asset-link").fill("https://example.com/sample-document")
  await file.getByRole("button", { name: "Create asset", exact: true }).click()
  await expect(file).toBeHidden()
  await expect(page.getByRole("status").filter({ hasText: "File saved" })).toBeVisible()
})

for (const width of [1440, 390]) {
  test(`project sponsorship is optional and the add-tab menu stays reachable (${width})`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    await page.goto(fixture)
    const section = page.getByRole("region", { name: "Project tab review" })
    await expect(section.getByRole("checkbox", { name: "Add Fiscal Sponsorship" })).not.toBeChecked()
    await section.getByRole("checkbox", { name: "Add Fiscal Sponsorship" }).check()
    await expect(section.getByRole("checkbox", { name: "Add Fiscal Sponsorship" })).toBeChecked()
    await expect(section.getByRole("tab", { name: "Fiscal Sponsorship", exact: true })).toHaveCount(0)
    const add = section.getByRole("button", { name: "Add project tab" })
    await add.scrollIntoViewIfNeeded()
    const bounds = await add.boundingBox()
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
    await add.click()
    await page.getByRole("menuitem", { name: "Fiscal Sponsorship", exact: true }).click()
    await expect(section.getByRole("tab", { name: "Fiscal Sponsorship", exact: true })).toHaveAttribute("aria-selected", "true")
    await expect(section.getByRole("tabpanel")).toContainText("Sample sponsorship tab added")
    const list = section.getByRole("tablist")
    expect(await list.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    const activeTab = section.getByRole("tab", { name: "Fiscal Sponsorship", exact: true })
    await expect.poll(() => activeTab.evaluate((element) => getComputedStyle(element, "::after").opacity)).toBe("1")
    await section.getByRole("tab", { name: "Tasks", exact: true }).click()
    await expect(section.getByRole("tab", { name: "Tasks", exact: true })).toHaveAttribute("aria-selected", "true")
    await expect.poll(() => activeTab.evaluate((element) => getComputedStyle(element, "::after").opacity)).toBe("0")
    expect(await section.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    await add.click()
    await expect(page.getByRole("menuitem", { name: "Fiscal Sponsorship (added)", exact: true })).toBeDisabled()
    await page.keyboard.press("Escape")
    await expect(add).toBeFocused()
  })
}


test("organization programs open the saved builder without autosaving on view", async ({ page }) => {
  const writes: string[] = []
  // Block every mutation during this read-only review, including regressions.
  await page.route("**/*", async (route) => {
    if (route.request().method() !== "GET" && route.request().method() !== "HEAD") {
      if (route.request().headers()["next-action"]) writes.push(route.request().url())
      await route.abort()
    } else await route.continue()
  })
  await page.goto(fixture)
  const section = page.getByRole("region", { name: "Organization programs review" })
  await section.getByRole("tab", { name: "Programs", exact: true }).click()
  await expect(section.getByText("Community mentorship", { exact: true })).toBeVisible()
  await section.getByRole("button", { name: "View / edit" }).click()
  const dialog = page.getByRole("dialog", { name: "Activity builder" })
  await expect(dialog).toBeVisible()
  await dialog.getByRole("button", { name: "Continue", exact: true }).click()
  await expect(dialog.getByLabel("Activity name", { exact: true })).toHaveValue("Community mentorship")
  // The existing autosave debounce is 700ms; reading must never trigger it.
  await page.waitForTimeout(1000)
  expect(writes).toEqual([])
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click()
  await expect(dialog).toBeHidden()
})
