import type { BrandIdentityDraft, StoredBrandAsset } from "../types"
import { buildBrandTokens, normalizeHex } from "./brand-identity"

type ZipEntry = { name: string; data: Uint8Array }

const encoder = new TextEncoder()

function writeUint16(view: DataView, offset: number, value: number) {
  view.setUint16(offset, value, true)
}

function writeUint32(view: DataView, offset: number, value: number) {
  view.setUint32(offset, value >>> 0, true)
}

function crc32(bytes: Uint8Array) {
  let crc = 0xffffffff
  for (const byte of bytes) {
    crc ^= byte
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1))
    }
  }
  return (crc ^ 0xffffffff) >>> 0
}

function concatenate(parts: Uint8Array[]) {
  const result = new Uint8Array(
    parts.reduce((sum, part) => sum + part.length, 0)
  )
  let offset = 0
  for (const part of parts) {
    result.set(part, offset)
    offset += part.length
  }
  return result
}

export function createBrowserZip(entries: ZipEntry[]) {
  const localParts: Uint8Array[] = []
  const centralParts: Uint8Array[] = []
  let localOffset = 0

  for (const entry of entries) {
    const name = encoder.encode(entry.name)
    const checksum = crc32(entry.data)
    const local = new Uint8Array(30 + name.length)
    const localView = new DataView(local.buffer)
    writeUint32(localView, 0, 0x04034b50)
    writeUint16(localView, 4, 20)
    writeUint16(localView, 6, 0x0800)
    writeUint16(localView, 8, 0)
    writeUint32(localView, 14, checksum)
    writeUint32(localView, 18, entry.data.length)
    writeUint32(localView, 22, entry.data.length)
    writeUint16(localView, 26, name.length)
    local.set(name, 30)
    localParts.push(local, entry.data)

    const central = new Uint8Array(46 + name.length)
    const centralView = new DataView(central.buffer)
    writeUint32(centralView, 0, 0x02014b50)
    writeUint16(centralView, 4, 20)
    writeUint16(centralView, 6, 20)
    writeUint16(centralView, 8, 0x0800)
    writeUint16(centralView, 10, 0)
    writeUint32(centralView, 16, checksum)
    writeUint32(centralView, 20, entry.data.length)
    writeUint32(centralView, 24, entry.data.length)
    writeUint16(centralView, 28, name.length)
    writeUint32(centralView, 42, localOffset)
    central.set(name, 46)
    centralParts.push(central)
    localOffset += local.length + entry.data.length
  }

  const centralDirectory = concatenate(centralParts)
  const end = new Uint8Array(22)
  const endView = new DataView(end.buffer)
  writeUint32(endView, 0, 0x06054b50)
  writeUint16(endView, 8, entries.length)
  writeUint16(endView, 10, entries.length)
  writeUint32(endView, 12, centralDirectory.length)
  writeUint32(endView, 16, localOffset)

  return concatenate([...localParts, centralDirectory, end])
}

function safeName(value: string) {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "nonprofit-brand"
  )
}

function readme(draft: BrandIdentityDraft) {
  const colors = draft.colors
    .map((color) => `- ${color.name}: ${normalizeHex(color.value)}`)
    .join("\n")
  return `${draft.organizationName} brand guide

${draft.tagline}

Purpose
${draft.purpose}

Audience
${draft.audience}

Logo use
${draft.logoGuidance}

Palette
${colors}

Typography
- Headings: ${draft.headingFont}
- Body: ${draft.bodyFont}
- Base size: ${draft.baseSize}px
- Scale ratio: ${draft.typeRatio}

Accessibility
Verify text and background combinations at the final size. Use a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text.

Generated by the Coach House public Brand Identity tool.
`
}

export async function buildBrandPackage(
  draft: BrandIdentityDraft,
  assets: StoredBrandAsset[]
) {
  const entries: ZipEntry[] = [
    {
      name: "brand/brand.json",
      data: encoder.encode(JSON.stringify(draft, null, 2)),
    },
    { name: "brand/tokens.css", data: encoder.encode(buildBrandTokens(draft)) },
    { name: "README.txt", data: encoder.encode(readme(draft)) },
  ]

  for (const asset of assets) {
    const extension = asset.name.includes(".")
      ? `.${asset.name.split(".").at(-1)?.toLowerCase()}`
      : ""
    entries.push({
      name: `assets/${asset.id}${extension}`,
      data: new Uint8Array(await asset.blob.arrayBuffer()),
    })
  }

  return {
    blob: new Blob([createBrowserZip(entries) as BlobPart], {
      type: "application/zip",
    }),
    filename: `${safeName(draft.organizationName)}-brand-kit.zip`,
  }
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement("a")
  anchor.href = url
  anchor.download = filename
  anchor.click()
  window.setTimeout(() => URL.revokeObjectURL(url), 0)
}
