import type { WorkspaceFinanceInput } from "../types"

export const WORKSPACE_FINANCE_SAMPLE_INPUT = {
  programs: [
    {
      id: "sample-youth-workshops",
      title: "Youth workshops",
      goalCents: 3_000_000,
      raisedCents: 2_000_000,
    },
    {
      id: "sample-community-studio",
      title: "Community studio",
      raisedCents: 1_000_000,
      budgetCents: 2_500_000,
    },
    {
      id: "sample-training-program",
      title: "Training program",
      goalCents: 2_000_000,
      raisedCents: 800_000,
    },
  ],
  opportunities: [
    {
      id: "sample-state-arts-grant",
      title: "State arts education grant",
      source: "Department of Cultural Affairs",
      dueAt: "2026-09-18T23:59:59.000Z",
      discoveredAt: "2026-08-08T15:00:00.000Z",
      status: "new",
    },
    {
      id: "sample-community-sponsorship",
      title: "Community impact sponsorship",
      source: "Northside Community Bank",
      dueAt: "2026-09-30T23:59:59.000Z",
      discoveredAt: "2026-08-07T15:00:00.000Z",
      status: "applied",
    },
    {
      id: "sample-youth-services-rfp",
      title: "Youth services partnership RFP",
      source: "County Youth Services",
      dueAt: "2026-10-12T23:59:59.000Z",
      discoveredAt: "2026-08-06T15:00:00.000Z",
      status: "saved",
    },
  ],
  opportunitiesState: "ready",
  records: [
    {
      id: "sample-donation-replacement",
      programId: "sample-youth-workshops",
      effectiveAt: "2026-08-08T14:00:00.000Z",
      sourceLabel: "Community giving",
      recordType: "donation",
      typeLabel: "Individual donations",
      amountCents: 1_200_000,
      currencyCode: "USD",
      direction: "in",
      status: "reconciled",
      sourceKind: "donations",
      correction: {
        correctionId: "sample-donation-correction",
        correctedAt: "2026-08-08T16:00:00.000Z",
        reason: "The source name was corrected.",
        relatedRecordId: "sample-donation-original",
        state: "replacement",
      },
    },
    {
      id: "sample-donation-original",
      programId: "sample-youth-workshops",
      effectiveAt: "2026-08-08T14:00:00.000Z",
      sourceLabel: "Community giving import",
      recordType: "donation",
      typeLabel: "Individual donations",
      amountCents: 1_200_000,
      currencyCode: "USD",
      direction: "in",
      status: "reconciled",
      sourceKind: "donations",
      correction: {
        correctionId: "sample-donation-correction",
        correctedAt: "2026-08-08T16:00:00.000Z",
        reason: "The source name was corrected.",
        relatedRecordId: "sample-donation-replacement",
        state: "corrected",
      },
    },
    {
      id: "sample-grant",
      programId: "sample-community-studio",
      effectiveAt: "2026-08-05T14:00:00.000Z",
      sourceLabel: "City Arts Fund",
      typeLabel: "Program grant",
      amountCents: 2_000_000,
      currencyCode: "USD",
      direction: "in",
      status: "reconciled",
      sourceKind: "grants",
    },
    {
      id: "sample-earned-revenue",
      programId: "sample-training-program",
      effectiveAt: "2026-08-02T14:00:00.000Z",
      sourceLabel: "Workshop registration",
      typeLabel: "Program revenue",
      amountCents: 450_000,
      currencyCode: "USD",
      direction: "in",
      status: "reconciled",
      sourceKind: "earned_revenue",
    },
    {
      id: "sample-recorded-donation",
      programId: "sample-youth-workshops",
      effectiveAt: "2026-07-31T14:00:00.000Z",
      sourceLabel: "Pending bank reference",
      recordType: "donation",
      typeLabel: "Individual donation",
      amountCents: 250_000,
      currencyCode: "USD",
      direction: "in",
      status: "recorded",
      sourceKind: "donations",
    },
    {
      id: "sample-other",
      programId: "sample-training-program",
      effectiveAt: "2026-07-29T14:00:00.000Z",
      sourceLabel: "Community partner",
      typeLabel: "Sponsorship",
      amountCents: 150_000,
      currencyCode: "USD",
      direction: "in",
      status: "reconciled",
      sourceKind: "other",
    },
  ],
  recordsState: "ready",
} satisfies WorkspaceFinanceInput
