export const organizationProjectSelectFields = [
  "id",
  "org_id",
  "canonical_org_id",
  "project_kind",
  "name",
  "description",
  "status",
  "priority",
  "progress",
  "start_date",
  "end_date",
  "client_name",
  "type_label",
  "duration_label",
  "tags",
  "member_labels",
  "task_count",
  "created_source",
  "starter_seed_key",
  "starter_seed_version",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
].join(", ")
