-- Align resource-map categories with the public /find taxonomy.

with top_categories(key, label, sort_order, marker_color, icon_name, aliases, description) as (
  values
    ('health', 'Health', 10, '#059669', 'heart-pulse', array['health', 'medical', 'clinic', 'care access', 'primary care'], 'Health care, prevention, insurance, navigation, and recovery.'),
    ('food', 'Food', 20, '#e11d48', 'utensils', array['food', 'meal', 'meals', 'pantry', 'groceries', 'nutrition'], 'Food access, groceries, meals, nutrition, and water support.'),
    ('housing', 'Housing', 30, '#4f46e5', 'bed', array['housing', 'shelter', 'homeless', 'rent', 'utility'], 'Shelter, housing stability, rent, utilities, and home repair.'),
    ('education', 'Education', 40, '#d97706', 'graduation-cap', array['education', 'school', 'student', 'learning', 'literacy'], 'Early childhood, K-12, adult learning, and college access.'),
    ('employment', 'Employment', 50, '#ea580c', 'briefcase-business', array['employment', 'jobs', 'workforce', 'career', 'placement'], 'Job search, skills, credentials, and entrepreneurship.'),
    ('finance', 'Finance', 60, '#0d9488', 'scale', array['finance', 'funding', 'benefits', 'cash', 'tax', 'credit'], 'Assistance, benefits, taxes, coaching, credit, and grants.'),
    ('legal', 'Legal', 70, '#7c3aed', 'scale', array['legal', 'rights', 'immigration', 'expungement', 'law'], 'Legal aid, rights, immigration, reentry, and documentation.'),
    ('family', 'Family', 80, '#db2777', 'heart-handshake', array['family', 'childcare', 'parenting', 'youth', 'seniors'], 'Children, parents, seniors, caregivers, veterans, and LGBTQ+ support.'),
    ('community', 'Community', 90, '#16a34a', 'users-round', array['community', 'mutual aid', 'neighbors', 'library', 'transportation'], 'Civic, cultural, recreation, transit, internet, and local support.'),
    ('emergency', 'Emergency', 100, '#dc2626', 'badge-plus', array['emergency', 'crisis', 'disaster', 'cooling', 'warming'], 'Crisis response, emergency shelter, disaster relief, and recovery.'),
    ('environment', 'Environment', 110, '#65a30d', 'droplets', array['environment', 'climate', 'sustainability', 'conservation', 'water'], 'Climate, conservation, water, energy, parks, and environmental justice.'),
    ('safety', 'Safety', 120, '#2563eb', 'heart-handshake', array['safety', 'violence prevention', 'street outreach', 'survivor'], 'Violence prevention, survivor support, outreach, and mediation.'),
    ('organizations', 'Organizations', 130, '#64748b', 'users-round', array['organizations', 'nonprofit', 'capacity', 'fiscal sponsorship'], 'Capacity building, grants, fundraising, training, and technical assistance.'),
    ('international', 'International', 140, '#0284c7', 'radio', array['international', 'refugee', 'asylum', 'humanitarian', 'global'], 'Refugee, asylum, humanitarian, global development, and international education.'),
    ('animals', 'Animals', 150, '#9333ea', 'users-round', array['animals', 'pet', 'veterinary', 'rescue', 'wildlife'], 'Animal welfare, pet support, veterinary assistance, rescue, and wildlife.')
)
insert into public.resource_map_categories (
  key,
  label,
  parent_key,
  sort_order,
  marker_color,
  icon_name,
  aliases,
  description
)
select
  key,
  label,
  null,
  sort_order,
  marker_color,
  icon_name,
  aliases,
  description
from top_categories
on conflict (key) do update set
  label = excluded.label,
  parent_key = excluded.parent_key,
  sort_order = excluded.sort_order,
  marker_color = excluded.marker_color,
  icon_name = excluded.icon_name,
  aliases = excluded.aliases,
  description = excluded.description,
  updated_at = timezone('utc', now());

with subcategories(parent_key, key, label, sort_order) as (
  values
    ('health', 'health_primary_care', 'Primary Care', 1),
    ('health', 'health_dental', 'Dental', 2),
    ('health', 'health_vision', 'Vision', 3),
    ('health', 'health_mental_health', 'Mental Health', 4),
    ('health', 'health_crisis_hotlines', 'Crisis & Hotlines', 5),
    ('health', 'health_substance_use_recovery', 'Substance Use & Recovery', 6),
    ('health', 'health_disability_services', 'Disability Services', 7),
    ('health', 'health_womens_health', 'Women''s Health', 8),
    ('health', 'health_mens_health', 'Men''s Health', 9),
    ('health', 'health_childrens_health', 'Children''s Health', 10),
    ('health', 'health_senior_health', 'Senior Health', 11),
    ('health', 'health_sexual_reproductive_health', 'Sexual & Reproductive Health', 12),
    ('health', 'health_chronic_illness', 'Chronic Illness', 13),
    ('health', 'health_preventive_care', 'Preventive Care', 14),
    ('health', 'health_insurance', 'Health Insurance', 15),
    ('health', 'health_care_navigation', 'Care Navigation', 16),
    ('food', 'food_food_pantries', 'Food Pantries', 1),
    ('food', 'food_community_meals', 'Community Meals', 2),
    ('food', 'food_groceries', 'Groceries', 3),
    ('food', 'food_nutrition', 'Nutrition', 4),
    ('food', 'food_water', 'Water', 5),
    ('food', 'food_baby_formula', 'Baby Formula', 6),
    ('food', 'food_school_meals', 'School Meals', 7),
    ('food', 'food_senior_meals', 'Senior Meals', 8),
    ('food', 'food_community_gardens', 'Community Gardens', 9),
    ('food', 'food_delivery', 'Food Delivery', 10),
    ('housing', 'housing_emergency_shelter', 'Emergency Shelter', 1),
    ('housing', 'housing_homeless_services', 'Homeless Services', 2),
    ('housing', 'housing_transitional_housing', 'Transitional Housing', 3),
    ('housing', 'housing_permanent_supportive_housing', 'Permanent Supportive Housing', 4),
    ('housing', 'housing_affordable_housing', 'Affordable Housing', 5),
    ('housing', 'housing_rental_assistance', 'Rental Assistance', 6),
    ('housing', 'housing_eviction_prevention', 'Eviction Prevention', 7),
    ('housing', 'housing_homeownership', 'Homeownership', 8),
    ('housing', 'housing_utility_assistance', 'Utility Assistance', 9),
    ('housing', 'housing_home_repair', 'Home Repair', 10),
    ('housing', 'housing_weatherization', 'Weatherization', 11),
    ('education', 'education_early_childhood', 'Early Childhood', 1),
    ('education', 'education_k_12', 'K-12', 2),
    ('education', 'education_after_school', 'After School', 3),
    ('education', 'education_tutoring', 'Tutoring', 4),
    ('education', 'education_literacy', 'Literacy', 5),
    ('education', 'education_esl_english', 'ESL / English', 6),
    ('education', 'education_ged', 'GED', 7),
    ('education', 'education_adult_education', 'Adult Education', 8),
    ('education', 'education_higher_education', 'Higher Education', 9),
    ('education', 'education_college_access', 'College Access', 10),
    ('education', 'education_scholarships', 'Scholarships', 11),
    ('education', 'education_financial_aid', 'Financial Aid', 12),
    ('education', 'education_vocational_trade_school', 'Vocational / Trade School', 13),
    ('education', 'education_stem', 'STEM', 14),
    ('education', 'education_arts_education', 'Arts Education', 15),
    ('education', 'education_special_education', 'Special Education', 16),
    ('education', 'education_digital_literacy', 'Digital Literacy', 17),
    ('education', 'education_career_counseling', 'Career Counseling', 18),
    ('education', 'education_mentorship', 'Mentorship', 19),
    ('education', 'education_life_skills', 'Life Skills', 20),
    ('employment', 'employment_job_search', 'Job Search', 1),
    ('employment', 'employment_resume_help', 'Resume Help', 2),
    ('employment', 'employment_interview_preparation', 'Interview Preparation', 3),
    ('employment', 'employment_career_coaching', 'Career Coaching', 4),
    ('employment', 'employment_workforce_development', 'Workforce Development', 5),
    ('employment', 'employment_skills_training', 'Skills Training', 6),
    ('employment', 'employment_apprenticeships', 'Apprenticeships', 7),
    ('employment', 'employment_certifications', 'Certifications', 8),
    ('employment', 'employment_internships', 'Internships', 9),
    ('employment', 'employment_entrepreneurship', 'Entrepreneurship', 10),
    ('employment', 'employment_small_business', 'Small Business', 11),
    ('employment', 'employment_professional_networking', 'Professional Networking', 12),
    ('finance', 'finance_cash_assistance', 'Cash Assistance', 1),
    ('finance', 'finance_emergency_assistance', 'Emergency Assistance', 2),
    ('finance', 'finance_benefits_enrollment', 'Benefits Enrollment', 3),
    ('finance', 'finance_public_benefits', 'Public Benefits', 4),
    ('finance', 'finance_tax_preparation', 'Tax Preparation', 5),
    ('finance', 'finance_financial_coaching', 'Financial Coaching', 6),
    ('finance', 'finance_budgeting', 'Budgeting', 7),
    ('finance', 'finance_banking', 'Banking', 8),
    ('finance', 'finance_credit_building', 'Credit Building', 9),
    ('finance', 'finance_debt_counseling', 'Debt Counseling', 10),
    ('finance', 'finance_microgrants', 'Microgrants', 11),
    ('finance', 'finance_small_business_funding', 'Small Business Funding', 12),
    ('legal', 'legal_legal_aid', 'Legal Aid', 1),
    ('legal', 'legal_immigration', 'Immigration', 2),
    ('legal', 'legal_family_law', 'Family Law', 3),
    ('legal', 'legal_housing_law', 'Housing Law', 4),
    ('legal', 'legal_consumer_protection', 'Consumer Protection', 5),
    ('legal', 'legal_civil_rights', 'Civil Rights', 6),
    ('legal', 'legal_reentry', 'Reentry', 7),
    ('legal', 'legal_expungement', 'Expungement', 8),
    ('legal', 'legal_mediation', 'Mediation', 9),
    ('legal', 'legal_identification_documentation', 'Identification & Documentation', 10),
    ('family', 'family_childcare', 'Childcare', 1),
    ('family', 'family_parenting', 'Parenting', 2),
    ('family', 'family_youth_services', 'Youth Services', 3),
    ('family', 'family_seniors', 'Seniors', 4),
    ('family', 'family_veterans', 'Veterans', 5),
    ('family', 'family_lgbtq', 'LGBTQ+', 6),
    ('family', 'family_domestic_violence', 'Domestic Violence', 7),
    ('family', 'family_foster_care', 'Foster Care', 8),
    ('family', 'family_adoption', 'Adoption', 9),
    ('family', 'family_family_support', 'Family Support', 10),
    ('family', 'family_caregivers', 'Caregivers', 11),
    ('community', 'community_faith_organizations', 'Faith Organizations', 1),
    ('community', 'community_volunteer_opportunities', 'Volunteer Opportunities', 2),
    ('community', 'community_community_organizing', 'Community Organizing', 3),
    ('community', 'community_civic_engagement', 'Civic Engagement', 4),
    ('community', 'community_voter_services', 'Voter Services', 5),
    ('community', 'community_events', 'Events', 6),
    ('community', 'community_recreation', 'Recreation', 7),
    ('community', 'community_sports', 'Sports', 8),
    ('community', 'community_arts_culture', 'Arts & Culture', 9),
    ('community', 'community_libraries', 'Libraries', 10),
    ('community', 'community_community_centers', 'Community Centers', 11),
    ('community', 'community_transportation', 'Transportation', 12),
    ('community', 'community_internet_access', 'Internet Access', 13),
    ('community', 'community_device_access', 'Device Access', 14),
    ('community', 'community_neighborhood_associations', 'Neighborhood Associations', 15),
    ('emergency', 'emergency_disaster_relief', 'Disaster Relief', 1),
    ('emergency', 'emergency_crisis_response', 'Crisis Response', 2),
    ('emergency', 'emergency_emergency_shelter', 'Emergency Shelter', 3),
    ('emergency', 'emergency_emergency_food', 'Emergency Food', 4),
    ('emergency', 'emergency_emergency_cash', 'Emergency Cash', 5),
    ('emergency', 'emergency_cooling_centers', 'Cooling Centers', 6),
    ('emergency', 'emergency_warming_centers', 'Warming Centers', 7),
    ('emergency', 'emergency_mutual_aid', 'Mutual Aid', 8),
    ('emergency', 'emergency_fire_recovery', 'Fire Recovery', 9),
    ('emergency', 'emergency_flood_recovery', 'Flood Recovery', 10),
    ('emergency', 'emergency_emergency_preparedness', 'Emergency Preparedness', 11),
    ('emergency', 'emergency_disaster_recovery', 'Disaster Recovery', 12),
    ('environment', 'environment_climate', 'Climate', 1),
    ('environment', 'environment_agriculture', 'Agriculture', 2),
    ('environment', 'environment_food_systems', 'Food Systems', 3),
    ('environment', 'environment_community_gardens', 'Community Gardens', 4),
    ('environment', 'environment_conservation', 'Conservation', 5),
    ('environment', 'environment_sustainability', 'Sustainability', 6),
    ('environment', 'environment_environmental_justice', 'Environmental Justice', 7),
    ('environment', 'environment_energy', 'Energy', 8),
    ('environment', 'environment_water', 'Water', 9),
    ('environment', 'environment_air_quality', 'Air Quality', 10),
    ('environment', 'environment_pollution', 'Pollution', 11),
    ('environment', 'environment_recycling', 'Recycling', 12),
    ('environment', 'environment_land_use', 'Land Use', 13),
    ('environment', 'environment_parks_open_space', 'Parks & Open Space', 14),
    ('safety', 'safety_violence_prevention', 'Violence Prevention', 1),
    ('safety', 'safety_street_outreach', 'Street Outreach', 2),
    ('safety', 'safety_community_safety', 'Community Safety', 3),
    ('safety', 'safety_gun_violence_prevention', 'Gun Violence Prevention', 4),
    ('safety', 'safety_human_trafficking', 'Human Trafficking', 5),
    ('safety', 'safety_survivor_support', 'Survivor Support', 6),
    ('safety', 'safety_conflict_mediation', 'Conflict Mediation', 7),
    ('organizations', 'organizations_fiscal_sponsorship', 'Fiscal Sponsorship', 1),
    ('organizations', 'organizations_capacity_building', 'Capacity Building', 2),
    ('organizations', 'organizations_grant_support', 'Grant Support', 3),
    ('organizations', 'organizations_fundraising', 'Fundraising', 4),
    ('organizations', 'organizations_board_development', 'Board Development', 5),
    ('organizations', 'organizations_strategic_planning', 'Strategic Planning', 6),
    ('organizations', 'organizations_research', 'Research', 7),
    ('organizations', 'organizations_technical_assistance', 'Technical Assistance', 8),
    ('organizations', 'organizations_training', 'Training', 9),
    ('organizations', 'organizations_volunteer_management', 'Volunteer Management', 10),
    ('international', 'international_refugee_services', 'Refugee Services', 1),
    ('international', 'international_asylum_support', 'Asylum Support', 2),
    ('international', 'international_humanitarian_aid', 'Humanitarian Aid', 3),
    ('international', 'international_global_development', 'Global Development', 4),
    ('international', 'international_disaster_response', 'Disaster Response', 5),
    ('international', 'international_international_education', 'International Education', 6),
    ('animals', 'animals_animal_welfare', 'Animal Welfare', 1),
    ('animals', 'animals_pet_food_assistance', 'Pet Food Assistance', 2),
    ('animals', 'animals_veterinary_assistance', 'Veterinary Assistance', 3),
    ('animals', 'animals_rescue', 'Rescue', 4),
    ('animals', 'animals_adoption', 'Adoption', 5),
    ('animals', 'animals_wildlife_conservation', 'Wildlife Conservation', 6)
),
top_categories as (
  select
    key,
    label,
    sort_order,
    marker_color,
    icon_name
  from public.resource_map_categories
  where parent_key is null
)
insert into public.resource_map_categories (
  key,
  label,
  parent_key,
  sort_order,
  marker_color,
  icon_name,
  aliases,
  description
)
select
  subcategories.key,
  subcategories.label,
  subcategories.parent_key,
  top_categories.sort_order + subcategories.sort_order,
  top_categories.marker_color,
  top_categories.icon_name,
  array[lower(subcategories.label)],
  subcategories.label || ' resources under ' || top_categories.label || '.'
from subcategories
join top_categories on top_categories.key = subcategories.parent_key
on conflict (key) do update set
  label = excluded.label,
  parent_key = excluded.parent_key,
  sort_order = excluded.sort_order,
  marker_color = excluded.marker_color,
  icon_name = excluded.icon_name,
  aliases = excluded.aliases,
  description = excluded.description,
  updated_at = timezone('utc', now());
